### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by rmbishop** [austintgriffith/eth.build#54]
npm install is not currently working.
It fails when trying to get ssh://git@github.com/hugomrdias/pull-ws.git
That repo is no longer present on github.

**Comment by rmbishop** [comment]
This issue seems to have been resolved.  pull-ws.git is once again available, due to hugomrdias creating a new repo for it on April 5th.

**Comment by sunsrt** [comment]
yarn  

任然存在报错
Error reporting still exists：
error An unexpected error occurred: "https://github.com/hugomrdias/pull-ws: ESOCKETTIMEDOUT"

**Comment by sunsrt** [comment]
yarn
Error reporting still exists：
error An unexpected error occurred: "https://github.com/hugomrdias/pull-ws: ESOCKETTIMEDOUT"
